language: objective-c
matrix:
  include:
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode8.3
cache:
  bundler: true
  cocoapods: true
  directories: []
branches:
  only:
    - master
before_install:
  # - brew update
  # - brew outdated xctool || brew upgrade xctool
  # - sudo motion update
  - (motion --version)
  - (ruby --version)
script:
  - bundle exec rake clean spec device_name='iPhone SE'
  - bundle exec rake clean spec platform=osx
  - bundle exec rake clean spec platform=tvos
